```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For fractions:
```{r}
library(MASS)
```
#salmon data

```{r}
library(rrcov)
library(mixtools)
par(mfrow=c(1,1), mar=c(4,4,2,1))
data(salmon)
plot(salmon$Freshwater,salmon$Marine,xlab="Freshwater",ylab="Marine",
     pch=rep(c(18,20),each=50),col=rep(c(2,4),each=50),main="")
legend("topright",legend=c("Alaskan","Canadian"),pch=c(18,20),col=c(2,4),cex=1)

# Method 1
x1 <- salmon[1:50,2:3]
x2 <- salmon[51:100,2:3]

# compute sample mean vectors:
x1.mean <- colMeans(x1)
x2.mean <- colMeans(x2)

# compute pooled estimate for the covariance matrix:
S.u <- 49*(var(x1)+var(x2))/98
w <- solve(S.u)%*%(x1.mean-x2.mean)
w0 <- -(x1.mean+x2.mean)%*%w/2
lines(salmon[,2],-(w[1]*salmon[,2]+w0)/w[2])

lines(x1.mean, x2.mean)

ellipse(x1.mean, var(x1), alpha = .05, npoints=250, newplot=FALSE)
ellipse(x2.mean, var(x2), alpha = .05, npoints=250, newplot=FALSE)


points(c(x2.mean[1],x1.mean[1]), c(x2.mean[2],x1.mean[2]), type='b', col='green')
mid <- (x1.mean + x2.mean)/2
points(c(w[1], mid[1]), c(w[2], mid[2]), type='b', col='orange')
```

```{r}
## Method 2: use function LDA in MASS package:

library(MASS)
lda.obj <- lda(Origin~Freshwater+Marine,data=salmon,prior=c(1,1)/2)
plda <- predict(object=lda.obj,newdata=salmon)

# Confusion matrix
table(salmon[,4],plda$class)
```

```{r}
#plot the decision line
gmean <- lda.obj$prior %*% lda.obj$means
const <- as.numeric(gmean %*%lda.obj$scaling)
slope <- - lda.obj$scaling[1] / lda.obj$scaling[2]
intercept <- const / lda.obj$scaling[2]
```

```{r}
#Plot decision boundary
plot(salmon[,2:3],pch=rep(c(18,20),each=50),col=rep(c(2,4),each=50))
abline(intercept, slope)
legend("topright",legend=c("Alaskan","Canadian"),pch=c(18,20),col=c(2,4))
```